apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-caddy-config
  labels:
    {{- include "domain-parking.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {
        email {{ .Values.caddy.config.email }}
        on_demand_tls {
            ask http://localhost:9000/check-host
        }
    }
    :80, :443 {
        tls {
            on_demand
        }
        rate_limit {
            key {remote_host}
            rate 2r/s
            burst 5
        }
        encode gzip
        root * /usr/share/caddy
        templates
        file_server
        log
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ .Values.caddy.config.parkedPage.title }}: {{`{{.Host}}`}}</title>
        <style>
            body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; text-align: center; }
            code { background: #eee; padding: 0.2em 0.4em; border-radius: 3px; }
        </style>
    </head>
    <body>
        <div>
            <h1>{{ .Values.caddy.config.parkedPage.heading }}</h1>
            <p>{{ .Values.caddy.config.parkedPage.message | replace "{{.Host}}" "<code>{{.Host}}</code>" }}</p>
        </div>
    </body>
    </html>
