apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-coredns-config
  labels:
    {{- include "domain-parking.labels" . | nindent 4 }}
data:
  Corefile: |
    . {
        auto

        rrl {
            requests-per-second 5
        }

        # Template for all other domains (catch-all)
        template IN A {
            match .
            answer "{{`{{ .Name }}`}} 60 IN A {{ .Values.loadBalancerIP }}"  # IP for your parked page
            fallthrough
        }

        # Auto-generate SOA + NS for any unmatched zone
        template IN SOA {
            answer "{{`{{ .Name }}`}} 3600 IN SOA ns.my.zone. hostmaster.my.zone. (
                        2025091701       ; serial
                        3600             ; refresh
                        600              ; retry
                        604800           ; expire
                        86400 )          ; minimum"
            fallthrough
        }

        template IN HTTPS {
            match .
            answer "{{`{{ .Name }}`}} 3600 IN HTTPS 1 . alpn=h2,h3"
            fallthrough
        }

        template IN NS {
            answer "{{`{{ .Name  }}`}} 3600 IN NS ns.my.zone."
            answer "{{`{{ .Name }}`}} 3600 IN NS ns2.my.zone."
            fallthrough
        }

        template IN AAAA {
            match .
            answer "{{`{{ .Name }}`}} 3600 IN SOA ns.my.zone. hostmaster.my.zone. 0 0 0 0 0"
            rcode NXDOMAIN
            fallthrough
        }

        template IN CAA {
            match .
            answer "{{`{{ .Name }}`}} 3600 IN SOA ns.my.zone. hostmaster.my.zone. 0 0 0 0 0"
            rcode NXDOMAIN
            fallthrough
        }

        cancel

        log
        errors
        bind 0.0.0.0
    }
